config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name='payments:order_list', permanent=False), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", admin.site.urls),
    # Payment System
    path("payments/", include("payments.urls", namespace="payments")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

payments/urls.py
from payments.views import (StatusListView, StatusCreateView, StatusDeleteView, StatusUpdateView,
                            OrderUpdateView, OrderDeleteView, OrderCreateView, OrderListView)
from django.urls import path


app_name = "payments"
urlpatterns = [
    path("order/", view=OrderListView.as_view(), name="order_list"),
    path("order/create/", view=OrderCreateView.as_view(), name="order_create"),
    path("order/update/<pk>/", view=OrderUpdateView.as_view(), name="order_update"),
    path("order/delete/<pk>/", view=OrderDeleteView.as_view(), name="order_delete"),
    path("status/", view=StatusListView.as_view(), name="status_list"),
    path("status/create/", view=StatusCreateView.as_view(), name="status_create"),
    path("status/update/<pk>/", view=StatusUpdateView.as_view(), name="status_update"),
    path("status/delete/<pk>/", view=StatusDeleteView.as_view(), name="status_delete"),

]

payments/models.py
import uuid

from django.db import models
from django.core.validators import MinValueValidator

from decimal import Decimal
from datetime import datetime


class OrderStatus(models.Model):
    """Status of order"""
    name = models.CharField("Status of Order", max_length=30, unique=True)

    class Meta:
        verbose_name = 'Order Statuse'

    def __str__(self):
        return self.name


class Order(models.Model):
    """Provide model for orders"""

    # ID orders are safer to store in UUID
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Deposit management info
    created_at = models.DateTimeField('Creation date', auto_now_add=True)
    purporse = models.CharField("Purpose of payment", max_length=30)
    status = models.ForeignKey(OrderStatus, related_name="orders",
                               on_delete=models.SET_NULL, null=True, blank=True)

    # Transaction info
    amount = models.DecimalField(
        'Amount', max_digits=12, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])

    class Meta:
        verbose_name = 'Payment Order'
        ordering = ('-created_at', )

    def __str__(self):
        return f'Deposit {self.id}: {self.amount} {self.status}'

payments/views.py
from payments.models import Order, OrderStatus
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView


# Create your views here.
class OrderListView(ListView):
    """List view for Order model"""
    template_name = "payments/payment_list.html"
    model = Order

class OrderCreateView(CreateView):
    """Create order view"""
    template_name = "payments/create_form.html"
    fields = ('purporse', 'status', 'amount')
    success_url = reverse_lazy('payments:order_list')
    model = Order

class OrderUpdateView(UpdateView):
    """Update order fields"""
    template_name = "payments/update_form.html"
    fields = ('purporse', 'status', 'amount')
    success_url = reverse_lazy('payments:order_list')
    model = Order

class OrderDeleteView(DeleteView):
    """Delete order"""
    template_name = "payments/delete_form.html"
    model = Order
    success_url = reverse_lazy('payments:order_list')


class StatusListView(ListView):
    """List view for status model"""
    template_name = "payments/status_list.html"
    model = OrderStatus


class StatusCreateView(CreateView):
    """Create status view"""
    template_name = "payments/create_form.html"
    fields = ('name', )
    success_url = reverse_lazy('payments:status_list')
    model = OrderStatus


class StatusUpdateView(UpdateView):
    """Update status fields"""
    template_name = "payments/update_form.html"
    fields = ('name', )
    success_url = reverse_lazy('payments:status_list')
    model = OrderStatus


class StatusDeleteView(DeleteView):
    """Delete status"""
    template_name = "payments/delete_form.html"
    model = OrderStatus
    success_url = reverse_lazy('payments:status_list')

templates/payments/_base.html
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h1><a href="{% url 'payments:order_list' %}">Payments</a> <a href="{% url 'payments:status_list' %}">Statuses</a></h1>
{% block content %}

{% endblock %}
</body>
</ul>
</html>

templates/payments/create_form.html
{% extends 'payments/_base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/payments/delete_form.html
{% extends 'payments/_base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/payments/payment_list.html
{% extends 'payments/_base.html' %}
{% block content %}
<ul>
    <h3><a href="{% url 'payments:order_create' %}">Create Order</a> </h3>
    <table>
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Purporse</th>
            <th>Status</th>
            <th>Edit</th>
            <th>Delete</th>

        </tr>
{% for payment in object_list %}
    <tr>
        <td>{{ payment.id }}</td>
        <td>{{ payment.created_at }}</td>
        <td>{{ payment.amount }}</td>
        <td>{{ payment.purporse }}</td>
        <td>{{ payment.status }}</td>
        <td><a href="{% url 'payments:order_update' pk=payment.id %}">Edit</a> </td>
        <td><a href="{% url 'payments:order_delete' pk=payment.id %}">Delete</a> </td>
    </tr>
{% empty %}
    <li>No payments yet.</li>
{% endfor %}
{% endblock %}
    </table>

templates/payments/status_list.html
{% extends 'payments/_base.html' %}
{% block content %}
<ul>
    <h3><a href="{% url 'payments:status_create' %}">Create Status</a> </h3>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>


        </tr>
{% for status in object_list %}
    <tr>
        <td>{{ status.id }}</td>
        <td>{{ status.name }}</td>
        <td><a href="{% url 'payments:status_update' pk=status.id %}">Edit</a> </td>
        <td><a href="{% url 'payments:status_delete' pk=status.id %}">Delete</a> </td>
    </tr>

{% empty %}
    <li>No payments yet.</li>
{% endfor %}
{% endblock %}
    </table>

templates/payments/update_form.html
{% extends 'payments/_base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}